(defun full-colors (str)
  (let ((len (length str))
        (red 0) (green 0) (yellow 0) (blue 0))
    (dotimes (i len)
      (let ((str-car (aref str i)))
        (cond ((char= str-car #\R)
               (incf red)
               (if (> (abs (- red green)) 1)
                   (return 'false)))
              ((char= str-car #\G)
               (incf green)
               (if (> (abs (- red green)) 1)
                   (return 'false)))
              ((char= str-car #\Y)
               (incf yellow)
               (if (> (abs (- yellow blue)) 1)
                   (return 'false)))
              (t (incf blue)
                 (if (> (abs (- yellow blue)) 1)
                     (return 'false))))))
    (if (and (eql red green) (eql yellow blue))
        'true
        'false)))

(dotimes (i (read))
  (format t "~:(~A~)~%" (full-colors (read-line))))
